FROM python:3.12-slim

WORKDIR /app

# Copie des requirements 
COPY src/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code source et du modèle
COPY src/api/v2/main.py .
COPY model/model.joblib ./model.joblib

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
