# nginx/nginx.conf

events {
    worker_connections 1024;
}

http {
    # Définit la zone de limitation
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # --- 2. LOGIQUE A/B TESTING ---
    # On regarde l'en-tête X-Experiment-Group. 
    # Si c'est 'debug', on envoie vers api-v2. Sinon (default), vers api-v1.
    map $http_x_experiment_group $upstream_choice {
        default "api-v1";
        "debug" "api-v2";
    }

    # --- 3. DEFINITION DES UPSTREAMS ---
    upstream api-v1 {
        server api-v1:8000; # Docker DNS gère les 3 réplicas automatiquement
    }

    upstream api-v2 {
        server api-v2:8000;
    }

    # --- 4. REDIRECTION HTTP VERS HTTPS  ---
    server {
        listen 80;
        server_name localhost; # Nom de domaine ou IP que ce bloc serveur gère
        
         # Redirige toutes les requêtes HTTP vers HTTPS
        return 301 https://$host$request_uri;
    }

    # --- 5. SERVEUR PRINCIPAL HTTPS ---
    server {
        listen 443 ssl; # Écoute sur le port 443 et active SSL
        server_name localhost; # Nom de domaine ou IP que ce serveur gère

        # # Chemins vers les certificats SSL à l'intérieur du conteneur Nginx 
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;
        
         # Protocoles et chiffrements SSL
        ssl_protocols TLSv1.2 TLSv1.3; # N'autorise que les versions modernes de TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # Liste des suites de chiffrement autorisées
        ssl_prefer_server_ciphers on; # Préfère les chiffrements du serveur

        # --- ENDPOINT /predict  ---
        # Toutes les requêtes qui commencent par /predict/ seront traitées ici
        location /predict {
            # Authentification Basique 
            auth_basic "Zone Protégée - Sentiment API";
            auth_basic_user_file /etc/nginx/.htpasswd; # Chemin vers le fichier .htpasswd dans le conteneur

            # Application du Rate Limit 
            limit_req zone=api_limit burst=5 nodelay;

            # Routage A/B Testing 
            proxy_pass http://$upstream_choice;

            # Headers Standards
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- MONITORING  ---
        location /nginx_status {
            stub_status on; # Active le module stub_status
            access_log off; # Ne pas logguer les accès à cet endpoint
            allow 127.0.0.1; # Autorise l'accès uniquement depuis localhost (l'exporter)
            allow 172.19.0.0/16; # Ou depuis le réseau Docker
            deny all; # Bloque tout autre accès
        }

        # --- ENDPOINT DE SANTE  ---
        location /health {
            auth_basic off;
            proxy_pass http://api-v1/health;
        }
    }
}